# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d210cc80cceef1f01b80320e8fcebd8594fc9f8056292c9979dafe3a8c53b1333383db43d74cda1f2852a3659216fbbb654ac64c833dfb6faacf1238e49a71da

test:
  secret_key_base: 6725e9f4acacc8b22d49760ab03e0ee3350356994e01c076779311b3cb0d567cc1ed46cd1215c03db83e7ea6b64c0142b0b5299784dcb91a7113083b465728d7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
